wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1662990711.012624
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      4: 3.7.13
      5: 0.13.3
      8:
      - 1
      - 5
      10:
      - 9
augmentFactor:
  desc: null
  value: 6
batchSize:
  desc: null
  value: 64
dataFile:
  desc: null
  value: /content/drive/MyDrive/second_layer_ai_model/SketchAI/SketchAI/dataset/NapkinData/train.json
include_fingerup:
  desc: null
  value: false
isResample:
  desc: null
  value: false
load_mode:
  desc: null
  value: train
modelPath:
  desc: null
  value: /content/drive/MyDrive/second_layer_ai_model/SketchAI/SketchAI/checkpoints/models/separate_arrow_module
model_inputs:
  desc: null
  value: coord_and_tang
pad:
  desc: null
  value: true
project_name:
  desc: null
  value: shape recognition - bidirectional rnn for arrow clf
test_size:
  desc: null
  value: 0.2
useSaliency:
  desc: null
  value: false
